name: "Deploy with Zappa"
description: "Deploys a Wagtail project using Zappa"

inputs:
  project-name:
    description: "Name of project"
    required: True
  deployment-target:
    description: "production or staging"
    required: True
  aws-access-key-id:
    description: ""
    required: True
  aws-secret-access-key:
    description: ""
    required: True
  django-secret-key:
    description: ""
    required: True
  uses-tailwind:
    description: "Does the project use Tailwind"
    required: false
    default: false
  elm-paths:
    description: "All paths to elm files ( '/wagtail/{{ project-name }}/{{ folder }}/elm' ) in project seperated by whitespace"
    required: false
    default: ''
  elm-version:
    description: "The version of Elm to be used to compile the elm files in the project"
    required: false
    default: 0.19.1


runs:
  using: "composite"
  steps:
    - name: Setup Node
      if: inputs.uses-tailwind!='false' || inputs.elm-paths!=''
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name:  Install and Compile Production Elm
      if: inputs.elm-paths!=''
      uses: Funbit-AS/gha-compile-elm@v1
      with:
        github-workspace: ${{ github.workspace }}
        elm-paths: ${{ inputs.elm-paths }}
        elm-version: ${{ inputs.elm-version }}

    - name: Tailwind - Install and Compile Production
      if: inputs.uses-tailwind!='false'
      run: |
        cd wagtail/${{ inputs.project-name }}/theme/static_src
        npm install
        npx tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css --minify
      shell: bash
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-central-1
      
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          **/requirements/common.txt
          **/requirements/production.txt
        
    - name: Setup Python Virtual env
      run: |
        python -m venv env
        source env/bin/activate
        pip --disable-pip-version-check install -r requirements/production.txt
      shell: bash
        
    - name: Collectstatic
      env:
        DJANGO_SECRET_KEY: ${{ inputs.django-secret-key }}
      run: |
        source env/bin/activate
        python manage.py collectstatic --noinput --settings=${{ inputs.project-name }}.settings.${{ inputs.deployment-target }}
      shell: bash
          
    - name: Update site with Zappa
      run: |
        source env/bin/activate
        zappa update ${{ inputs.deployment-target }}
      shell: bash
      
    - name: Migrate database
      if: success() || failure()
      run: |
        source env/bin/activate
        zappa manage ${{ inputs.deployment-target }} migrate
      shell: bash